### ISSUE TITLE
Mac Error

### ISSUE THREAD

**Issue by jacoby149-pt** [Kofituo/rifgen#3]
`#![feature]` may not be used on the stable release channel
 --> /Users/jacob/.cargo/registry/src/github.com-1ecc6299db9ec823/rifgen-0.1.51/src/lib.rs:1:12
  |
1 | #![feature(drain_filter)]
  |            ^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `rifgen` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `rifgen` due to previous error

**Comment by Kofituo** [comment]
Hii there
You need to use nightly to compile the create
It seems you currently have the stable in use
Please install nightly and get back to me

**Comment by jacoby149-pt** [comment]
Thanks! I installed nightly and it built it with nightly and it ran smoothly!
