### ISSUE TITLE
Error "Invalid rust file" if any non rust file is in the src folder

### ISSUE THREAD

**Issue by fastcoding** [Kofituo/rifgen#4]
I don't think it's reasonable that build should fail in these cases: 

- case 1: when using with cxx crate, there are normally c++ files in the src directory or any subdirectories.
- case 2: sometimes MacOS creates a hidden .DS_Store file in the source folder.

It can be quickly fixed by adding a file extension check in generator_lib.rs:visit_dirs(dir,cb) function:
```rust
            if path.is_dir() {
                visit_dirs(&path, cb)?;
            } else if path.ends_with(".rs"){
                cb(&entry);
            }
```

**Comment by Kofituo** [comment]
Hi there, thanks for the suggestion. 
I'm not currently with my pc. Could you please create a pr so I update the repository?

**Comment by Kofituo** [comment]
Updated now!
